#!/bin/bash

_sleep=3
_php=/usr/bin/php5.6
_c=0
_script=
_limit=999
_params=

addparam() {
	if [ "$_script" == "" ]; then
		_script=$1;
	else
		_params="$_params $1";
	fi
}

while [ "$1" != "" ]; do
    case $1 in
    -s | --sleep           ) shift;_sleep=$1;;
		-c | --clear           ) _c=1;;
		-l | --limit           ) shift;_l=$1;;
		-5 | --php56           ) _php=/usr/bin/php5.6;;
		-7 | --php7						 ) _php=/usr/bin/php7.0;;
    *                      ) addparam $1;;
    esac
    shift
done


for ((i=1; i<_limit; i++));
do

	if [ $_c -eq 1 ]; then
		clear
	else
		echo;
		echo;
		echo "-------------------------------------------------------------------------------";
	fi

  echo "Try #" $i;
	$_php -f $_script -- $params
	if [ $_c -eq 0 ]; then
		echo "-------------------------------------------------------------------------------";
		echo;
		echo;
	fi

	sleep $_sleep
done
